import type { Recipe } from "./types";

/**
 * Curated Gulf recipe catalog — v0. Ranges reflect typical home
 * preparations across the Gulf; restaurant portions run 30-50 % higher
 * on the top end. Everything here is halal by default. When you know
 * you have accurate macros for a specific version, override in the UI
 * before logging.
 *
 * NEEDS DIETITIAN REVIEW before public launch — my ranges are educated
 * estimates. TODO: hand this file to a Gulf-based RD for a pass.
 */
export const RECIPES: Recipe[] = [
  // ── BREAKFAST ────────────────────────────────────────────────────
  {
    id: "foul-medames",
    name_en: "Foul medames",
    name_ar: "فول مدمس",
    category: "breakfast",
    cuisine: "levantine",
    servings: 1,
    prep_time_min: 5,
    cook_time_min: 5,
    kcal_low: 320,
    kcal_high: 420,
    protein_g_low: 15,
    protein_g_high: 20,
    carb_g_low: 40,
    carb_g_high: 55,
    fat_g_low: 10,
    fat_g_high: 15,
    ingredients: [
      { name_en: "fava beans (canned)", name_ar: "فول", qty: "1 cup" },
      { name_en: "olive oil", name_ar: "زيت زيتون", qty: "1 tbsp" },
      { name_en: "lemon", name_ar: "ليمون", qty: "1/2" },
      { name_en: "garlic", name_ar: "ثوم", qty: "2 cloves" },
      { name_en: "cumin", name_ar: "كمون", qty: "1/2 tsp" },
    ],
    steps: [
      "Warm the beans in their liquid.",
      "Mash lightly, keep some whole.",
      "Stir in olive oil, lemon, crushed garlic, cumin.",
      "Serve with khubz and tomato salad.",
    ],
    tags: ["halal", "vegetarian", "vegan", "high-protein", "ramadan-friendly"],
  },
  {
    id: "shakshuka",
    name_en: "Shakshuka",
    name_ar: "شكشوكة",
    category: "breakfast",
    cuisine: "levantine",
    servings: 1,
    prep_time_min: 5,
    cook_time_min: 15,
    kcal_low: 380,
    kcal_high: 480,
    protein_g_low: 18,
    protein_g_high: 24,
    carb_g_low: 20,
    carb_g_high: 28,
    fat_g_low: 22,
    fat_g_high: 30,
    ingredients: [
      { name_en: "eggs", name_ar: "بيض", qty: "2" },
      { name_en: "tomato sauce", name_ar: "صلصة طماطم", qty: "1 cup" },
      { name_en: "onion", name_ar: "بصل", qty: "1/2" },
      { name_en: "bell pepper", name_ar: "فلفل", qty: "1/2" },
      { name_en: "olive oil", name_ar: "زيت زيتون", qty: "1 tbsp" },
    ],
    steps: [
      "Sauté onion + pepper in oil until soft.",
      "Add tomato + spices, simmer 5 min.",
      "Crack eggs into sauce, cover, cook until whites set.",
    ],
    tags: ["halal", "vegetarian", "high-protein"],
  },
  {
    id: "balaleet",
    name_en: "Balaleet",
    name_ar: "بلاليط",
    category: "breakfast",
    cuisine: "emirati",
    servings: 1,
    prep_time_min: 5,
    cook_time_min: 15,
    kcal_low: 520,
    kcal_high: 680,
    protein_g_low: 14,
    protein_g_high: 20,
    carb_g_low: 65,
    carb_g_high: 85,
    fat_g_low: 20,
    fat_g_high: 30,
    ingredients: [
      { name_en: "vermicelli", qty: "1 cup" },
      { name_en: "sugar", qty: "3 tbsp" },
      { name_en: "cardamom", name_ar: "هيل", qty: "1/2 tsp" },
      { name_en: "saffron", name_ar: "زعفران", qty: "pinch" },
      { name_en: "eggs (for omelet on top)", qty: "2" },
      { name_en: "ghee", name_ar: "سمن", qty: "1 tbsp" },
    ],
    steps: [
      "Boil vermicelli, drain.",
      "Toss with sugar, cardamom, saffron, ghee.",
      "Top with a thin omelet.",
    ],
    tags: ["halal", "vegetarian"],
    notes: "Very high sugar — treat as a weekend or celebration breakfast.",
  },
  {
    id: "labneh-zaatar",
    name_en: "Labneh with zaatar + olive oil",
    name_ar: "لبنة مع زعتر وزيت زيتون",
    category: "breakfast",
    cuisine: "levantine",
    servings: 1,
    prep_time_min: 3,
    cook_time_min: 0,
    kcal_low: 240,
    kcal_high: 340,
    protein_g_low: 12,
    protein_g_high: 18,
    carb_g_low: 8,
    carb_g_high: 14,
    fat_g_low: 16,
    fat_g_high: 24,
    ingredients: [
      { name_en: "labneh", name_ar: "لبنة", qty: "3 tbsp" },
      { name_en: "olive oil", qty: "1 tbsp" },
      { name_en: "zaatar", name_ar: "زعتر", qty: "1 tbsp" },
      { name_en: "cucumber + tomato", qty: "1/2 cup" },
    ],
    steps: [
      "Spread labneh on a plate, drizzle olive oil, dust with zaatar.",
      "Serve with cucumber, tomato, and pita.",
    ],
    tags: ["halal", "vegetarian", "high-protein"],
  },
  {
    id: "manakish-zaatar",
    name_en: "Manakish zaatar",
    name_ar: "مناقيش زعتر",
    category: "breakfast",
    cuisine: "levantine",
    servings: 1,
    prep_time_min: 10,
    cook_time_min: 10,
    kcal_low: 380,
    kcal_high: 520,
    protein_g_low: 10,
    protein_g_high: 14,
    carb_g_low: 45,
    carb_g_high: 60,
    fat_g_low: 16,
    fat_g_high: 24,
    ingredients: [
      { name_en: "flatbread dough (or pita)", qty: "1 piece" },
      { name_en: "zaatar", qty: "2 tbsp" },
      { name_en: "olive oil", qty: "2 tbsp" },
    ],
    steps: [
      "Mix zaatar with olive oil to paste.",
      "Spread on dough, bake 8-10 min at 220 °C.",
    ],
    tags: ["halal", "vegetarian", "vegan"],
  },
  // ── LUNCH / DINNER ────────────────────────────────────────────────
  {
    id: "chicken-machboos",
    name_en: "Chicken machboos",
    name_ar: "مجبوس دجاج",
    category: "lunch",
    cuisine: "emirati",
    servings: 1,
    prep_time_min: 15,
    cook_time_min: 60,
    kcal_low: 650,
    kcal_high: 850,
    protein_g_low: 42,
    protein_g_high: 55,
    carb_g_low: 70,
    carb_g_high: 90,
    fat_g_low: 18,
    fat_g_high: 30,
    ingredients: [
      { name_en: "chicken thigh (skinless)", qty: "180 g" },
      { name_en: "basmati rice", qty: "3/4 cup dry" },
      { name_en: "onion", qty: "1" },
      { name_en: "dried lime (loomi)", name_ar: "لومي", qty: "1" },
      { name_en: "baharat spice mix", name_ar: "بهارات", qty: "1 tbsp" },
      { name_en: "tomato", qty: "1" },
      { name_en: "ghee or oil", qty: "1 tbsp" },
    ],
    steps: [
      "Brown chicken with onion, tomato, spices.",
      "Add loomi + water, simmer 25 min.",
      "Remove chicken, cook rice in the broth.",
      "Return chicken on top to serve.",
    ],
    tags: ["halal", "high-protein"],
  },
  {
    id: "kabsa-lamb",
    name_en: "Lamb kabsa",
    name_ar: "كبسة لحم",
    category: "lunch",
    cuisine: "saudi",
    servings: 1,
    prep_time_min: 15,
    cook_time_min: 90,
    kcal_low: 780,
    kcal_high: 1000,
    protein_g_low: 42,
    protein_g_high: 55,
    carb_g_low: 75,
    carb_g_high: 95,
    fat_g_low: 28,
    fat_g_high: 42,
    ingredients: [
      { name_en: "lamb shoulder", qty: "180 g" },
      { name_en: "basmati rice", qty: "3/4 cup dry" },
      { name_en: "onion", qty: "1" },
      { name_en: "kabsa spice mix", qty: "1 tbsp" },
      { name_en: "tomato paste", qty: "1 tbsp" },
    ],
    steps: [
      "Brown lamb with onion, add spices + tomato paste.",
      "Simmer 60 min until tender.",
      "Cook rice in the broth 20 min.",
    ],
    tags: ["halal", "high-protein"],
    notes: "Restaurant portions of kabsa can hit 1200-1500 kcal — this is a home-cooked single serving.",
  },
  {
    id: "chicken-biryani",
    name_en: "Chicken biryani",
    name_ar: "برياني دجاج",
    category: "lunch",
    cuisine: "gulf-fusion",
    servings: 1,
    prep_time_min: 20,
    cook_time_min: 60,
    kcal_low: 720,
    kcal_high: 920,
    protein_g_low: 38,
    protein_g_high: 50,
    carb_g_low: 75,
    carb_g_high: 95,
    fat_g_low: 24,
    fat_g_high: 38,
    ingredients: [
      { name_en: "chicken thigh", qty: "180 g" },
      { name_en: "basmati rice", qty: "3/4 cup dry" },
      { name_en: "yogurt", qty: "3 tbsp" },
      { name_en: "biryani spice mix", qty: "1 tbsp" },
      { name_en: "fried onion", qty: "1 tbsp" },
      { name_en: "ghee", qty: "1 tbsp" },
    ],
    steps: [
      "Marinate chicken in yogurt + spices 30 min.",
      "Par-boil rice.",
      "Layer chicken + rice, top with fried onion + ghee, cook covered 25 min.",
    ],
    tags: ["halal", "high-protein"],
  },
  {
    id: "mandi-chicken",
    name_en: "Chicken mandi",
    name_ar: "مندي دجاج",
    category: "lunch",
    cuisine: "yemeni",
    servings: 1,
    prep_time_min: 15,
    cook_time_min: 90,
    kcal_low: 680,
    kcal_high: 880,
    protein_g_low: 42,
    protein_g_high: 55,
    carb_g_low: 70,
    carb_g_high: 88,
    fat_g_low: 20,
    fat_g_high: 32,
    ingredients: [
      { name_en: "chicken (whole quarter)", qty: "200 g" },
      { name_en: "basmati rice", qty: "3/4 cup dry" },
      { name_en: "hawaij spice mix", qty: "1 tbsp" },
      { name_en: "raisins", qty: "1 tbsp" },
    ],
    steps: [
      "Rub chicken with hawaij, roast 60 min at 180 °C.",
      "Cook rice in chicken broth 20 min.",
      "Serve chicken atop rice, garnish with raisins.",
    ],
    tags: ["halal", "high-protein"],
  },
  {
    id: "shish-taouk",
    name_en: "Shish taouk (grilled chicken skewers)",
    name_ar: "شيش طاووق",
    category: "dinner",
    cuisine: "levantine",
    servings: 1,
    prep_time_min: 10,
    cook_time_min: 15,
    kcal_low: 340,
    kcal_high: 460,
    protein_g_low: 42,
    protein_g_high: 55,
    carb_g_low: 4,
    carb_g_high: 8,
    fat_g_low: 14,
    fat_g_high: 24,
    ingredients: [
      { name_en: "chicken breast", qty: "180 g" },
      { name_en: "yogurt", qty: "2 tbsp" },
      { name_en: "lemon", qty: "1/2" },
      { name_en: "garlic", qty: "2 cloves" },
      { name_en: "olive oil", qty: "1 tbsp" },
    ],
    steps: [
      "Marinate chicken in yogurt + lemon + garlic + oil for 30 min.",
      "Skewer, grill 3-4 min per side.",
      "Serve with garlic sauce + salad.",
    ],
    tags: ["halal", "high-protein", "low-carb"],
  },
  {
    id: "grilled-hammour",
    name_en: "Grilled hammour with saluna",
    name_ar: "هامور مشوي مع صالونة",
    category: "dinner",
    cuisine: "emirati",
    servings: 1,
    prep_time_min: 10,
    cook_time_min: 25,
    kcal_low: 420,
    kcal_high: 560,
    protein_g_low: 40,
    protein_g_high: 52,
    carb_g_low: 20,
    carb_g_high: 32,
    fat_g_low: 16,
    fat_g_high: 26,
    ingredients: [
      { name_en: "hammour fillet", qty: "180 g" },
      { name_en: "tomato + onion sauce", qty: "1/2 cup" },
      { name_en: "coriander", qty: "small handful" },
      { name_en: "olive oil", qty: "1 tbsp" },
    ],
    steps: [
      "Grill or pan-sear hammour 4 min/side.",
      "Simmer tomato+onion sauce with coriander.",
      "Plate fish over sauce.",
    ],
    tags: ["halal", "high-protein"],
  },
  {
    id: "chicken-shawarma",
    name_en: "Chicken shawarma wrap",
    name_ar: "شاورما دجاج",
    category: "lunch",
    cuisine: "levantine",
    servings: 1,
    prep_time_min: 5,
    cook_time_min: 5,
    kcal_low: 540,
    kcal_high: 780,
    protein_g_low: 32,
    protein_g_high: 45,
    carb_g_low: 45,
    carb_g_high: 60,
    fat_g_low: 22,
    fat_g_high: 38,
    ingredients: [
      { name_en: "chicken shawarma meat", qty: "150 g" },
      { name_en: "arabic bread", qty: "1 wrap" },
      { name_en: "toum (garlic sauce)", qty: "1 tbsp" },
      { name_en: "pickles", qty: "small handful" },
    ],
    steps: [
      "Fill bread with meat + toum + pickles.",
      "Roll tightly, toast on a hot pan 1 min per side.",
    ],
    tags: ["halal", "high-protein"],
    notes: "Street shawarmas trend to the top of the range (extra oil, fries added). Home wrap is the low end.",
  },
  {
    id: "mixed-grill",
    name_en: "Mixed grill (skewers + kofta)",
    name_ar: "مشاوي مشكلة",
    category: "dinner",
    cuisine: "levantine",
    servings: 1,
    prep_time_min: 10,
    cook_time_min: 15,
    kcal_low: 620,
    kcal_high: 900,
    protein_g_low: 55,
    protein_g_high: 72,
    carb_g_low: 8,
    carb_g_high: 15,
    fat_g_low: 36,
    fat_g_high: 55,
    ingredients: [
      { name_en: "chicken skewer", qty: "100 g" },
      { name_en: "beef kofta", qty: "100 g" },
      { name_en: "lamb kabab", qty: "80 g" },
      { name_en: "salad + garlic sauce", qty: "1 side" },
    ],
    steps: ["Grill all skewers to preferred doneness. Serve with salad."],
    tags: ["halal", "high-protein", "low-carb"],
  },
  {
    id: "harees",
    name_en: "Harees",
    name_ar: "هريس",
    category: "lunch",
    cuisine: "emirati",
    servings: 1,
    prep_time_min: 10,
    cook_time_min: 180,
    kcal_low: 480,
    kcal_high: 640,
    protein_g_low: 28,
    protein_g_high: 40,
    carb_g_low: 55,
    carb_g_high: 70,
    fat_g_low: 14,
    fat_g_high: 24,
    ingredients: [
      { name_en: "cracked wheat", qty: "1/2 cup dry" },
      { name_en: "chicken or lamb", qty: "120 g" },
      { name_en: "water", qty: "3 cups" },
      { name_en: "ghee (topping)", qty: "1 tbsp" },
      { name_en: "cinnamon (topping)", qty: "pinch" },
    ],
    steps: [
      "Simmer wheat + meat + water 2-3 hours until porridge-like.",
      "Salt to taste.",
      "Top with ghee + cinnamon.",
    ],
    tags: ["halal", "high-protein", "ramadan-friendly"],
  },
  {
    id: "molokhia",
    name_en: "Molokhia stew",
    name_ar: "ملوخية",
    category: "lunch",
    cuisine: "egyptian",
    servings: 1,
    prep_time_min: 10,
    cook_time_min: 30,
    kcal_low: 420,
    kcal_high: 560,
    protein_g_low: 32,
    protein_g_high: 42,
    carb_g_low: 40,
    carb_g_high: 55,
    fat_g_low: 12,
    fat_g_high: 22,
    ingredients: [
      { name_en: "molokhia (frozen or dried)", qty: "1 cup" },
      { name_en: "chicken", qty: "150 g" },
      { name_en: "garlic + coriander", qty: "1 tbsp" },
      { name_en: "rice (side)", qty: "1/2 cup cooked" },
    ],
    steps: [
      "Simmer chicken with garlic + spices.",
      "Add molokhia, simmer 15 min.",
      "Serve over rice.",
    ],
    tags: ["halal", "high-protein"],
  },
  // ── SNACK ─────────────────────────────────────────────────────────
  {
    id: "hummus-veggies",
    name_en: "Hummus + veggies + pita",
    name_ar: "حمص وخضار",
    category: "snack",
    cuisine: "levantine",
    servings: 1,
    prep_time_min: 3,
    cook_time_min: 0,
    kcal_low: 260,
    kcal_high: 360,
    protein_g_low: 10,
    protein_g_high: 15,
    carb_g_low: 30,
    carb_g_high: 42,
    fat_g_low: 10,
    fat_g_high: 16,
    ingredients: [
      { name_en: "hummus", qty: "3 tbsp" },
      { name_en: "cucumber + carrot sticks", qty: "1 cup" },
      { name_en: "pita (1/2)", qty: "1/2 piece" },
    ],
    steps: ["Plate everything. Eat."],
    tags: ["halal", "vegetarian", "vegan"],
  },
  {
    id: "sambousek-beef",
    name_en: "Sambousek (beef, baked)",
    name_ar: "سمبوسك لحم",
    category: "snack",
    cuisine: "levantine",
    servings: 1,
    prep_time_min: 15,
    cook_time_min: 15,
    kcal_low: 220,
    kcal_high: 320,
    protein_g_low: 10,
    protein_g_high: 16,
    carb_g_low: 22,
    carb_g_high: 30,
    fat_g_low: 8,
    fat_g_high: 14,
    ingredients: [
      { name_en: "sambousek dough", qty: "3 pieces" },
      { name_en: "beef mince", qty: "60 g" },
      { name_en: "onion + spices", qty: "1 tbsp" },
    ],
    steps: ["Fill dough with beef+onion, fold triangles.", "Bake 15 min at 200 °C."],
    tags: ["halal", "high-protein", "ramadan-friendly"],
    notes: "Fried sambousek adds 60-100 kcal per piece.",
  },
  {
    id: "dates-coffee",
    name_en: "Dates + Arabic coffee (3 dates)",
    name_ar: "تمر وقهوة عربية",
    category: "snack",
    cuisine: "gulf-fusion",
    servings: 1,
    prep_time_min: 1,
    cook_time_min: 0,
    kcal_low: 80,
    kcal_high: 110,
    protein_g_low: 1,
    protein_g_high: 2,
    carb_g_low: 20,
    carb_g_high: 28,
    fat_g_low: 0,
    fat_g_high: 1,
    ingredients: [
      { name_en: "medjool dates", qty: "3" },
      { name_en: "Arabic coffee (gahwa)", qty: "1 small cup" },
    ],
    steps: ["Serve dates with a small cup of gahwa."],
    tags: ["halal", "vegetarian", "vegan", "ramadan-friendly"],
  },
  // ── DESSERT ───────────────────────────────────────────────────────
  {
    id: "luqaimat",
    name_en: "Luqaimat (5 pieces)",
    name_ar: "لقيمات",
    category: "dessert",
    cuisine: "emirati",
    servings: 1,
    prep_time_min: 15,
    cook_time_min: 15,
    kcal_low: 320,
    kcal_high: 480,
    protein_g_low: 4,
    protein_g_high: 8,
    carb_g_low: 45,
    carb_g_high: 65,
    fat_g_low: 12,
    fat_g_high: 22,
    ingredients: [
      { name_en: "flour + yeast dough", qty: "1/4 cup" },
      { name_en: "oil (for frying)", qty: "1 tbsp absorbed" },
      { name_en: "date syrup", qty: "2 tbsp" },
    ],
    steps: ["Drop dough balls into hot oil, fry until golden.", "Drain and drizzle with date syrup."],
    tags: ["halal", "vegetarian", "ramadan-friendly"],
    notes: "Restaurant portions run 10+ pieces. This assumes 5.",
  },
  // ── DRINK ─────────────────────────────────────────────────────────
  {
    id: "karak",
    name_en: "Karak chai",
    name_ar: "كرك",
    category: "drink",
    cuisine: "gulf-fusion",
    servings: 1,
    prep_time_min: 5,
    cook_time_min: 5,
    kcal_low: 90,
    kcal_high: 160,
    protein_g_low: 3,
    protein_g_high: 5,
    carb_g_low: 15,
    carb_g_high: 25,
    fat_g_low: 2,
    fat_g_high: 6,
    ingredients: [
      { name_en: "evaporated milk", qty: "1/4 cup" },
      { name_en: "water", qty: "1/2 cup" },
      { name_en: "black tea", qty: "1 tsp" },
      { name_en: "cardamom", qty: "pinch" },
      { name_en: "sugar", qty: "1-2 tsp" },
    ],
    steps: ["Boil water + tea + cardamom 3 min.", "Add milk + sugar, simmer 2 min more."],
    tags: ["halal", "vegetarian"],
    notes: "Cafeteria versions push sugar higher — 200+ kcal common.",
  },
];

export function findRecipe(id: string): Recipe | null {
  return RECIPES.find((r) => r.id === id) ?? null;
}

export function recipesByCategory(cat: Recipe["category"]): Recipe[] {
  return RECIPES.filter((r) => r.category === cat);
}
